export default {
  COMMON: {
    LOGO: '/images/logo.png',
    LOGO_LOGIN: '/images/logo-login.png',
    AVATAR: '/images/icons/user.png',
    STORE: '/images/icons/store.png',
    BACKGROUND_LOGIN: '/images/background-login.jpg',
    NOTIFICATION: '/images/icons/notification.png',
    REFRESH: '/images/icons/refresh.png',
    VIDEO: '/images/icons/video.png',
    LOG: '/images/icons/log.png',
  },
  MENU: {
    module_config: '/images/menu/module_config.png',
    deploy: '/images/menu/deploy.png',
    //
    project: '/images/menu/project.png',
    sim_result: '/images/menu/sim_result.png',
    device_reservation: '/images/menu/device_reservation.png',
    device_deploy: '/images/menu/device_deploy.png',
    device_result: '/images/menu/device_result.png',
    source_code: '/images/menu/source_code.png',
    project_setting: '/images/menu/project_setting.png',
  },
  ICONS: {
    search: '/images/icons/search.png',
    close: '/images/icons/close.png',
  },
  LOWCODEEDITOR: {
    logo: '/images/lowCodeEditor/logo.svg',
    search: '/images/lowCodeEditor/searchIcon.svg',
    closed: '/images/lowCodeEditor/closedIcon.svg',
    skillsSubTree: '/images/lowCodeEditor/skillsSubTreeIcon.svg',
    caretDown: '/images/lowCodeEditor/caretDown.svg',
    dragDot: '/images/lowCodeEditor/dragDot.svg',
    skillsIcon: '/images/lowCodeEditor/skillsIcon.svg',
    caretRight: '/images/lowCodeEditor/caretRight.svg',
    selector: '/images/lowCodeEditor/selector.svg',
    decorator: '/images/lowCodeEditor/decorator.svg',
    sequence: '/images/lowCodeEditor/sequence.svg',
    copy: '/images/lowCodeEditor/copy.svg',
    arrowRight: '/images/lowCodeEditor/arrowRight.svg',
    arrowLeft: '/images/lowCodeEditor/arrowLeft.svg',
    rootIcon: '/images/lowCodeEditor/rootIcon.svg',
    sequenceIcon: '/images/lowCodeEditor/sequenceIcon.svg',
    skillIcon: '/images/lowCodeEditor/skillIcon.svg',
    decoratorIcon: '/images/lowCodeEditor/decoratorIcon.svg',
    subTreeIcon: '/images/lowCodeEditor/subTreeIcon.svg',
    userIcon: '/images/lowCodeEditor/userIcon.svg',
    timeIcon: '/images/lowCodeEditor/timeIcon.svg',
    caretRight2: '/images/lowCodeEditor/caretRight2.svg',
    pause: '/images/lowCodeEditor/pause.svg',
    square: '/images/lowCodeEditor/square.svg',
    stepBack: '/images/lowCodeEditor/stepBack.svg',
    stepForward: '/images/lowCodeEditor/stepForward.svg',
  },
}
