// user
export const USER_LIST_KEY = 'USER_LIST_KEY'
export const USER_DETAIL_KEY = 'USER_DETAIL_KEY'

// deploy
export const DEPLOY_LIST_KEY = 'DEPLOY_LIST_KEY'
export const DEPLOY_DETAIL_KEY = 'DEPLOY_DETAIL_KEY'

// video
export const VIDEO_LIST_KEY = 'VIDEO_LIST_KEY'
export const VIDEO_DETAIL_KEY = 'VIDEO_DETAIL_KEY'

// log
export const LOG_LIST_KEY = 'LOG_LIST_KEY'
export const LOG_DETAIL_KEY = 'LOG_DETAIL_KEY'

// project
export const PROJECT_LIST_KEY = 'PROJECT_LIST_KEY'
export const PROJECT_DETAIL_KEY = 'PROJECT_DETAIL_KEY'

// module
export const MODULE_LIST_KEY = 'MODULE_LIST_KEY'
export const MODULE_DETAIL_KEY = 'MODULE_DETAIL_KEY'

// module-set
export const MODULE_SET_LIST_KEY = 'MODULE_SET_LIST_KEY'
export const MODULE_SET_DETAIL_KEY = 'MODULE_SET_DETAIL_KEY'
export const MODULE_SET_SELECTION_KEY = 'MODULE_SET_SELECTION_KEY'

// module-config
export const MODULE_CONFIG_LIST_KEY = 'MODULE_CONFIG_LIST_KEY'
export const MODULE_CONFIG_DETAIL_KEY = 'MODULE_CONFIG_DETAIL_KEY'
export const MODULE_CONFIG_SELECTION_KEY = 'MODULE_CONFIG_SELECTION_KEY'

// robot
export const ROBOT_LIST_KEY = 'ROBOT_LIST_KEY'
// site
export const SITE_LIST_KEY = 'SITE_LIST_KEY'
