export const FORMAT_STRING = {
  date: 'YYYY/MM/DD',
  date_minus: 'YYYY-MM-DD',
  date_str: 'YYYY年MM月DD日',
  datetime: 'YYYY/MM/DD HH:mm',
  datetime_full: 'YYYY/MM/DD HH:mm:ss',
  fulltime: 'YYYY/MM/DD(ddd) HH:mm',
  datetime_str: 'YYYY年MM月DD日 HH:mm',
  datetime_full_str: 'YYYY年MM月DD日 HH:mm:ss',
  date_week_str: 'MM月DD日',
  today: '今日HH:mm',
  time: 'HH:mm',
  time_full: 'HH:mm:ss',
  time_today: 'HH:mm 今日',
  time_tomorrow: 'HH:mm 今日',
  time_month_day: 'MMM DD',
}
